site_name: AIList
# site_logo: img/logo_caravel_dark.svg
site_url: http://ailist.databio.org/
repo_url: http://github.com/databio/AIList
paper_link: https://doi.org/10.1093/bioinformatics/btz407
theme: databio
use_directory_urls: true

nav:
  - Getting started:
    - Introduction: index.md
    - Installation and Hello World!: introduction.md
    - Benchmarks: benchmarks.md

  - Reference:
    - Usage: usage.md
    - Support: support.md

plugins:
  - search
  - databio:
      jupyter_build: "docs/autodoc_build"
      autodoc_modules: null
      usage_template: "docs/usage_template.md"
      usage_cmds:
        -"$CODEBASE/AIList/bin/AIList --help"
